# Default values for aether-operations-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
fullnameOverride: "aether-operations-api"

image:
  repository: onosproject/aether-operations-api
  tag: "{{ .Chart.AppVersion }}"
  pullPolicy: IfNotPresent
  pullSecrets: []

aetherOperationsAPI:
  logLevel: info
  dataSources:
    onosConfig: onos-config:5150
    onosTopo: onos-topo:5150
  servers:
    grpc:
      host: 0.0.0.0
      port: 50060
    http:
      host: 0.0.0.0
      port: 8080
      corsOrigins:
        - http://localhost:3000
