// Code generated by proroc-gen-graphql, DO NOT EDIT.
package v1

import (
	"context"

	"github.com/graphql-go/graphql"
	"github.com/pkg/errors"
	"github.com/ysugimoto/grpc-graphql-gateway/runtime"
	"google.golang.org/grpc"
)

var (
	gql__type_EnterpriseId  *graphql.Object      // message EnterpriseId in api/v1/roc.proto
	gql__input_EnterpriseId *graphql.InputObject // message EnterpriseId in api/v1/roc.proto
)

func Gql__type_EnterpriseId() *graphql.Object {
	if gql__type_EnterpriseId == nil {
		gql__type_EnterpriseId = graphql.NewObject(graphql.ObjectConfig{
			Name: "V1_Type_EnterpriseId",
			Fields: graphql.Fields{
				"enterpriseId": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_EnterpriseId
}

func Gql__input_EnterpriseId() *graphql.InputObject {
	if gql__input_EnterpriseId == nil {
		gql__input_EnterpriseId = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "V1_Input_EnterpriseId",
			Fields: graphql.InputObjectConfigFieldMap{
				"enterpriseId": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_EnterpriseId
}

// graphql__resolver_RocApi is a struct for making query, mutation and resolve fields.
// This struct must be implemented runtime.SchemaBuilder interface.
type graphql__resolver_RocApi struct {

	// Automatic connection host
	host string

	// grpc dial options
	dialOptions []grpc.DialOption

	// grpc client connection.
	// this connection may be provided by user
	conn *grpc.ClientConn
}

// new_graphql_resolver_RocApi creates pointer of service struct
func new_graphql_resolver_RocApi(conn *grpc.ClientConn) *graphql__resolver_RocApi {
	return &graphql__resolver_RocApi{
		conn:        conn,
		host:        "localhost:50051",
		dialOptions: []grpc.DialOption{},
	}
}

// CreateConnection() returns grpc connection which user specified or newly connected and closing function
func (x *graphql__resolver_RocApi) CreateConnection(ctx context.Context) (*grpc.ClientConn, func(), error) {
	// If x.conn is not nil, user injected their own connection
	if x.conn != nil {
		return x.conn, func() {}, nil
	}

	// Otherwise, this handler opens connection with specified host
	conn, err := grpc.DialContext(ctx, x.host, x.dialOptions...)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}

// GetQueries returns acceptable graphql.Fields for Query.
func (x *graphql__resolver_RocApi) GetQueries(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{
		"getApplications": &graphql.Field{
			Type: Gql__type_Applications(),
			Args: graphql.FieldConfigArgument{
				"enterpriseId": &graphql.ArgumentConfig{
					Type: graphql.String,
				},
			},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req EnterpriseId
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for getApplications")
				}
				client := NewRocApiClient(conn)
				resp, err := client.GetApplications(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC GetApplications")
				}
				return resp, nil
			},
		},
	}
}

// GetMutations returns acceptable graphql.Fields for Mutation.
func (x *graphql__resolver_RocApi) GetMutations(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{}
}

// Register package divided graphql handler "without" *grpc.ClientConn,
// therefore gRPC connection will be opened and closed automatically.
// Occasionally you may worry about open/close performance for each handling graphql request,
// then you can call RegisterRocApiGraphqlHandler with *grpc.ClientConn manually.
func RegisterRocApiGraphql(mux *runtime.ServeMux) error {
	return RegisterRocApiGraphqlHandler(mux, nil)
}

// Register package divided graphql handler "with" *grpc.ClientConn.
// this function accepts your defined grpc connection, so that we reuse that and never close connection inside.
// You need to close it maunally when application will terminate.
// Otherwise, you can specify automatic opening connection with ServiceOption directive:
//
// service RocApi {
//    option (graphql.service) = {
//        host: "host:port"
//        insecure: true or false
//    };
//
//    ...with RPC definitions
// }
func RegisterRocApiGraphqlHandler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return mux.AddHandler(new_graphql_resolver_RocApi(conn))
}
