// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RocApiClient is the client API for RocApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RocApiClient interface {
	GetEnterprises(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Enterprise, error)
	GetApplications(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Applications, error)
}

type rocApiClient struct {
	cc grpc.ClientConnInterface
}

func NewRocApiClient(cc grpc.ClientConnInterface) RocApiClient {
	return &rocApiClient{cc}
}

func (c *rocApiClient) GetEnterprises(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Enterprise, error) {
	out := new(Enterprise)
	err := c.cc.Invoke(ctx, "/roc.RocApi/GetEnterprises", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rocApiClient) GetApplications(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Applications, error) {
	out := new(Applications)
	err := c.cc.Invoke(ctx, "/roc.RocApi/GetApplications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RocApiServer is the server API for RocApi service.
// All implementations must embed UnimplementedRocApiServer
// for forward compatibility
type RocApiServer interface {
	GetEnterprises(context.Context, *Empty) (*Enterprise, error)
	GetApplications(context.Context, *Empty) (*Applications, error)
	mustEmbedUnimplementedRocApiServer()
}

// UnimplementedRocApiServer must be embedded to have forward compatible implementations.
type UnimplementedRocApiServer struct {
}

func (UnimplementedRocApiServer) GetEnterprises(context.Context, *Empty) (*Enterprise, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnterprises not implemented")
}
func (UnimplementedRocApiServer) GetApplications(context.Context, *Empty) (*Applications, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplications not implemented")
}
func (UnimplementedRocApiServer) mustEmbedUnimplementedRocApiServer() {}

// UnsafeRocApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RocApiServer will
// result in compilation errors.
type UnsafeRocApiServer interface {
	mustEmbedUnimplementedRocApiServer()
}

func RegisterRocApiServer(s grpc.ServiceRegistrar, srv RocApiServer) {
	s.RegisterService(&RocApi_ServiceDesc, srv)
}

func _RocApi_GetEnterprises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocApiServer).GetEnterprises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/roc.RocApi/GetEnterprises",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocApiServer).GetEnterprises(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RocApi_GetApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RocApiServer).GetApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/roc.RocApi/GetApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RocApiServer).GetApplications(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RocApi_ServiceDesc is the grpc.ServiceDesc for RocApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RocApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roc.RocApi",
	HandlerType: (*RocApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnterprises",
			Handler:    _RocApi_GetEnterprises_Handler,
		},
		{
			MethodName: "GetApplications",
			Handler:    _RocApi_GetApplications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/roc.proto",
}
