schema:
  - gen/graph/applications/v1/applications.graphql

exec:
  filename: gen/graph/applications/v1/generated.go
  package: application

model:
  filename: gen/graph/applications/v1/model.go
  package: application

autobind:
  - "github.com/onosproject/scaling-umbrella/gen/go/applications/v1"