schema:
#  - api/v1/enterprise.graphql
  - gen/enterprises/v1/enterprises.graphql

exec:
  filename: gen/graph/enterprises/v1/generated.go
  package: enterprise

model:
  filename: gen/graph/enterprises/v1/model.go
  package: enterprise

autobind:
  - "github.com/onosproject/scaling-umbrella/api/enterprises/v1"