schema:
  - api/v1/application.graphql

exec:
#  filename: api/v1/gqlgen/application/generated.go
  filename: gen/graph/application/v1/generated.go
  package: application

model:
#  filename: api/v1/gqlgen/application/model.go
  filename: gen/graph/application/v1/model.go
  package: application

autobind:
  - "github.com/onosproject/scaling-umbrella/api/applications/v1"